#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Kazumichi Suzuki(ketunii3@gmail.com)
# SPDX-License-Identifier: BSD-3-Clause

lAFword = ["apple "
        , "banana "
        , "cherry "
        , "door "
        , "ear "
        , "fork "]

for iOdd, oddAFword in enumerate( lAFword[0::2] ):
    print(f"A-F odd word: {oddAFword}")

for iEven, evenAFword in enumerate( lAFword[1::2] ):
    print(f"A-F even word: {evenAFword}")

