#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Kazumichi Suzuki(ketunii3@gmail.com)
# SPDX-License-Identifier: BSD-3-Clause

import sys

totalVal=0

for val in sys.stdin:
    try:
        totalVal += int(val)
    except:
        totalVal += float(val)

print(f"{totalVal}")
