#!/usr/bin/python3
import sys

totalVal=0

for val in sys.stdin:
    try:
        totalVal += int(val)
    except:
        totalVal += float(val)

print(f"Total is [{totalVal}], "+f"{type(totalVal)}")
